### PR TITLE
new snippets w/ descriptions, README modified

### PR DESCRIPTION
**Pull request by renatocfrancisco**
- 10 new snippets, with descriptions.
- changed README.md, two badges, new list of snippets.

This is the first time i contribute on a snippets repository. 
I found it and even used some of your snippets for one of my projects. Thought it was cool and i think i can help, even though, extremely new to PySimpleGUI.

@acezx-programer  What do you think about the descriptions? And the "${values}" on some of the snippets? Do you have a better idea on how to display the commands on the readme?

### CODE REVIEW

**Comment by acezx-programer** [comment]
Hi there! 
thanks for contributing, I made this extension as a side project and never thought anybody would contribute.
I think it is great because I never really know how to add good descriptions, thanks again!
I would love to update my extension to v2.0.0 with your version with some minor changes such as: added credits/changed versions in files

**Comment by renatocfrancisco** [comment]
@acezx-programer most of the descriptions are from the documentation. don't know why you closed the pull request.

**Comment by acezx-programer** [comment]
I mean, should I reopen it?
I already updated the GitHub with v2.0.0 with the credits and stuff, sorry I'm extremely new to github stuff

**Comment by renatocfrancisco** [comment]
@acezx-programer well, now that you updated the repository, **there is no use of opening the pull request (that had all those changes)**.
When someone wants to collaborate, you need to check the commits/changes and then confirm to [merge the pull request.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request)

**Comment by acezx-programer** [comment]
I'm sorry, I'm extremely new to this stuff, I usually just browse and never deal with repos before

**Pull request closed without merging**
